- name: Home
  # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
  # hide-desktop-navigation: true
  columns:
    - size: small
      widgets:
        - type: calendar
          first-day-of-week: monday

        - type: rss
          limit: 10
          collapse-after: 3
          cache: 12h
          feeds:
            - url: https://selfh.st/rss/
              title: selfh.st
            - url: https://ciechanow.ski/atom.xml
            - url: https://www.joshwcomeau.com/rss.xml
              title: Josh Comeau
            - url: https://samwho.dev/rss.xml
            - url: https://ishadeed.com/feed.xml
              title: Ahmad Shadeed

        - type: twitch-channels
          channels:
            - popstacular
            - purzbeats
            - theprimeagen
            - j_blow
            - piratesoftware
            - cohhcarnage
            - christitustech
            - EJ_SA

    - size: full
      widgets:
        - type: group
          widgets:
            - type: hacker-news
            - type: lobsters

        - type: videos
          channels:
            - UC9r9HYFxEQOBXSopFS61ZWg # Meidas Touch
            - UCXuqSBlHAE6Xw-yeJA0Tunw # Linus Tech Tips
            - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
            - UCsBjURrPoezykLs9EqgamOA # Fireship
            - UCBJycsmduvYEL83R_U4JriQ # Marques Brownlee
            - UCHnyfMqiRRG1u-2MsSQLbXA # Veritasium

        - type: group
          widgets:
            - type: reddit
              subreddit: technology
              show-thumbnails: true
            - type: reddit
              subreddit: ankara
              show-thumbnails: true
            - type: reddit
              subreddit: selfhosted
              show-thumbnails: true
            - type: reddit
              subreddit: spokane
              show-thumbnails: true
            - type: reddit
              subreddit: vettech
              show-thumbnails: true


    - size: small
      widgets:
        - type: weather
          location: Spokane, USA
          units: metric # alternatively "imperial"
          hour-format: 24h # alternatively "24h"
          # Optionally hide the location from being displayed in the widget
          # hide-location: true

        - type: markets
          markets:
            - symbol: SPY
              name: S&P 500
            - symbol: NVDA
              name: NVIDIA
            - symbol: DJT
              name: Trump
            - symbol: AAPL
              name: Apple
            - symbol: MSFT
              name: Microsoft
            - symbol: TSLA 
              name: Tesla

        - type: releases
          cache: 1d
          # Without authentication the Github API allows for up to 60 requests per hour. You can create a
          # read-only token from your Github account settings and use it here to increase the limit.
          # token: ...
          repositories:
            - glanceapp/glance
            - go-gitea/gitea
            - immich-app/immich
            - syncthing/syncthing

        - type: custom-api
          title: Random Fact
          cache: 3h
          url: https://uselessfacts.jsph.pl/api/v2/facts/random
          template: |
            <p class="size-h4 color-paragraph">{{ .JSON.String "text" }}</p>

        - type: custom-api
          title: Cat hall of Fame (From CaaS)
          cache: 1m
          url: https://cataas.com/api/cats?limit=${NUMBER_OF_CATS}&tags=${CAT_TAGS}
          headers:
              Accept: application/json
          template: |
              {{if eq (len (.JSON.Array "")) 0}}
              <div class="widget-error-header">
                  <p class="color-negative size-h3">Uh oh</p>
                  <svg class="widget-error-icon" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126ZM12 15.75h.007v.008H12v-.008Z"></path>
                  </svg>
              </div>
              <p style="font-size: var(--font-size-h4);">No cat was found with those tags, perhaps you should try with fewer tags! ฅ՞•ﻌ•՞ฅ</p>
              {{else}}
              <div class="cards-grid">
                  {{range .JSON.Array ""}}
                  <div style="display: flex; justify-content:center;">
                      <img src="https://cataas.com/cat/{{.String "id"}}?type=medium" style="object-fit: cover; border-radius: 10px;" class="card">
                  </div>
                  {{end}} 
              </div>
              {{end}}
        
